alter table "public"."listener_song_likes" drop constraint "listener_song_likes_listener_id_fkey";

alter table "public"."listener_song_stream" drop constraint "listener_song_stream_listener_id_fkey";

create table "public"."listener_song_library" (
    "id" bigint generated by default as identity not null,
    "listener_id" uuid,
    "song_id" bigint,
    "added_on" timestamp with time zone default now()
);


alter table "public"."listener_song_stream" alter column "listener_id" set not null;

CREATE UNIQUE INDEX listener_song_library_pkey ON public.listener_song_library USING btree (id);

alter table "public"."listener_song_library" add constraint "listener_song_library_pkey" PRIMARY KEY using index "listener_song_library_pkey";

alter table "public"."listener_song_library" add constraint "public_listener_song_library_listener_id_fkey" FOREIGN KEY (listener_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."listener_song_library" validate constraint "public_listener_song_library_listener_id_fkey";

alter table "public"."listener_song_library" add constraint "public_listener_song_library_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."listener_song_library" validate constraint "public_listener_song_library_song_id_fkey";

alter table "public"."listener_song_likes" add constraint "public_listener_song_likes_listener_id_fkey" FOREIGN KEY (listener_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."listener_song_likes" validate constraint "public_listener_song_likes_listener_id_fkey";

alter table "public"."listener_song_stream" add constraint "public_listener_song_stream_listener_id_fkey" FOREIGN KEY (listener_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."listener_song_stream" validate constraint "public_listener_song_stream_listener_id_fkey";

grant delete on table "public"."listener_song_library" to "anon";

grant insert on table "public"."listener_song_library" to "anon";

grant references on table "public"."listener_song_library" to "anon";

grant select on table "public"."listener_song_library" to "anon";

grant trigger on table "public"."listener_song_library" to "anon";

grant truncate on table "public"."listener_song_library" to "anon";

grant update on table "public"."listener_song_library" to "anon";

grant delete on table "public"."listener_song_library" to "authenticated";

grant insert on table "public"."listener_song_library" to "authenticated";

grant references on table "public"."listener_song_library" to "authenticated";

grant select on table "public"."listener_song_library" to "authenticated";

grant trigger on table "public"."listener_song_library" to "authenticated";

grant truncate on table "public"."listener_song_library" to "authenticated";

grant update on table "public"."listener_song_library" to "authenticated";

grant delete on table "public"."listener_song_library" to "service_role";

grant insert on table "public"."listener_song_library" to "service_role";

grant references on table "public"."listener_song_library" to "service_role";

grant select on table "public"."listener_song_library" to "service_role";

grant trigger on table "public"."listener_song_library" to "service_role";

grant truncate on table "public"."listener_song_library" to "service_role";

grant update on table "public"."listener_song_library" to "service_role";


